services:
  dnsmasq:
    build: .                         # ‚Üê This line tells it to build from the Dockerfile in the current directory
    container_name: dnsmasq
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./custom-hosts.conf:/etc/dnsmasq.d/custom-hosts.conf
    cap_add:
      - NET_ADMIN
    environment:
      - DNS1=1.1.1.1
      - DNS2=8.8.8.8