services:
  dnsmasq:
    image: my-dnsmasq-vim
    container_name: dnsmasq
    hostname: dns.corp.internal
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      # Mount the file from current directory into container
      - ./custom-hosts.conf:/etc/dnsmasq.d/custom-hosts.conf
    cap_add:
      - NET_ADMIN
    environment:
      - DNS1=1.1.1.1
      - DNS2=8.8.8.8