services:
  dnsmasq:
    image: dockurr/dnsmasq
    container_name: dnsmasq
    hostname: dns.corp.internal
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./custom-hosts.conf:/etc/dnsmasq.d/custom-hosts.conf:ro
    cap_add:
      - NET_ADMIN
    # Optional: set upstream DNS servers
    environment:
      - DNS1=1.0.0.1
      - DNS2=1.1.1.1