services:
  dnsmasq:
    build: .
    container_name: dnsmasq
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./config/dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ./config/hosts.custom:/etc/hosts.custom:ro
    cap_add:
      - NET_ADMIN