services:
  dnsmasq:
    build: .
    container_name: dnsmasq
    hostname: dns.corp.internal
    domainname: corp.internal
    restart: unless-stopped
    dns: 127.0.0.1
    dns_search:
      - corp.internal
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./config/dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ./config/hosts.custom:/etc/hosts.custom:ro
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      dns_net:
        ipv4_address: 172.20.0.53

networks:
  dns_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1