services:
  dnsmasq:
    image: strm/dnsmasq:latest
    container_name: dnsmasq
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      DNSMASQ_CONF: /etc/dnsmasq.conf
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ./custom-hosts:/etc/dnsmasq-hosts:ro
      - ./dnsmasq.leases:/var/lib/misc/dnsmasq.leases
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: "host"  # Uses host network stack