services:
  dnsmasq:
    image: strm/dnsmasq:latest
    container_name: dnsmasq
    restart: unless-stopped
    network_mode: host  # No "ports" section needed now
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - NET_BIND_SERVICE
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ./custom-hosts:/etc/dnsmasq-hosts:ro