version: '3.8'

services:
  vcf-depot:
    build: .
    container_name: vcf-offline-depot
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./depot_data:/depot
      - ./nginx.conf:/etc/nginx/sites-enabled/default
      - ./certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro
      - ./certs/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    restart: unless-stopped